name: Test SSG移植 (调用脚本)
on:
  workflow_dispatch:

jobs:
  test-ssg:
    runs-on: ubuntu-latest
    steps:
      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y git curl python3

      - name: 安装 repo
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: 拉取内核源码
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/${{ github.repository }}.git -b main -m oneplus_ace_pro_v.xml --depth=1
          repo sync

      - name: 执行 SSG 移植脚本
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/add_ssg.sh
          cd kernel_workspace
          $GITHUB_WORKSPACE/scripts/add_ssg.sh
